import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./nav/NavBar";
import SignalRProvider from "./providers/SignalRProvider";
import { getCurrentUser } from "./actions/authActions";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Carties",
  description: "Generated by create next app",
};

export const dynamic = 'force-dynamic';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body>
        <SessionProvider>
          <NavBar />
          <main className="container mx-auto px-5 pt-5">
            <SignalRProvider>
              {children}
            </SignalRProvider>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
